config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :keywords, only: [:index, :show] do
    collection {post :import}
  end

  use_doorkeeper
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
    	resources :keywords, only: :index do
        collection do
          post :import
          get :search_keyword
          get :search_adwords_urls
          get :search_all_urls
        end
  	  end
    end
  end	

  get 'static_pages/home', as: 'home'
  #get 'static_pages/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :keyword, presence: true

  def self.search(search_params)
    return search_keyword(search_params[:search_keyword]) if search_params[:search_keyword].present?
    return search_adwords_urls(search_params[:search_keyword]) if search_params[:search_adwords_urls].present?
    search_url(search_params[:search_url]) if search_params[:search_url].present?
  end

  private

  def self.search_keyword(term)
    binding.pry
    if term
      self.where('keyword LIKE ?', "%#{term}%")
    else
      self.all
    end
  end

  def self.search_adwords_urls(term)
    if term
      # Concatenate all urls and use || as seprator
      # ILIKE for matching patterns 
      self.where("array_to_string(ads_top_urls, '||') ILIKE :pattern OR 
        array_to_string(ads_bottom_urls, '||') ILIKE  :pattern ", pattern: "%#{term}%")
    else
      self.all
    end
  end

  def self.search_url(term)
    if term
      self.where("array_to_string(ads_top_urls, '||') ILIKE :pattern OR 
        array_to_string(ads_bottom_urls, '||') ILIKE  :pattern OR
        array_to_string(non_ads_urls, '||') ILIKE  :pattern ", pattern: "%#{term}%")
    else
      self.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/keywords_controller.rb
module Api
  module V1
  	class KeywordsController < ApplicationController
    	#skip_before_action :verify_authenticity_token
  	  respond_to :json
  	  before_action :doorkeeper_authorize!
  	  def index
  	  	respond_with Keyword.all.order(keyword: :asc)
  	  end

  	  def import
  	  	file = params.values[0].tempfile
  	  	if file != nil
  	  		Keyword.destroy_all
  	  		Keyword.import(file) 
  	  	end
  	  	redirect_to api_v1_keywords_path
  	  end

  	  def search_keyword
  	  	if params.present? && params[:term].present?
  	  		respond_with Keyword.search_keyword(params[:term]) 
  	  	else
          redirect_to api_v1_keywords_path
        end
  	  end

  	  def search_adwords_urls
  	  	if params.present? && params[:term].present?
   			respond_with Keyword.search_adwords_urls(params[:term])
  	  	else
          redirect_to api_v1_keywords_path
        end
  	  end

  	  def search_all_urls
  	  	if params.present? && params[:term].present?
  	  		respond_with Keyword.search_url(params[:term])
  	  	else
          redirect_to api_v1_keywords_path
        end
  	  end

  	  def show
  	  end
	  end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :authenticate_user!

  def index
    @keywords = if is_performing_search?
                  Keyword.search(search_params).paginate(page: params[:page], per_page: 10) 
                else 
                  Keyword.all.order(keyword: :asc).paginate(page: params[:page], per_page: 10)
                end

  	@count = @keywords.count

    respond_to do |format|
      format.html
      format.pdf do
        pdf = KeywordsReportPdf.new(@keywords)
        send_data pdf.render, filename: "Keywords Report.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def import
  	if params[:file]
      #binding.pry
  		ScrapingJob.perform_later(params[:file].path) 
      flash[:success] = "Uploaded Successfuly!"
      redirect_to keywords_path
  	else
      flash[:alert] = "Can't read CSV file or it's empty"
      render :index
    end
    
  end

  def show
    @keyword = Keyword.find(params[:id])
  end

  private 
  def is_performing_search?
    params.has_key?(:search_keyword) || params.has_key?(:search_adwords_urls) || params.has_key?(:search_url)
  end

  def search_params
    params.permit(:search_keyword, :search_adwords_urls, :search_url)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/views/keywords/index.html.erb
<div class="container">
  <div class="row well">
    <%= form_tag(import_keywords_path, multipart: true) do %>
      <div class="col-md-3">
        <%= file_field_tag :file, class: 'btn' %>
      </div>
      <div class="col-md-9">
         <%= submit_tag("Import", class: 'btn btn-primary') %>
      </div>
    <% end %>    
  </div>

  <div class="row">
    <div class="well col-xs-4">
      <%= form_tag keywords_path, :method => 'get' do %>
        <%= text_field_tag :search_keyword, params[:search_keyword] %>
        <%= submit_tag "Search Keywords" %>
      <% end %>
    </div>

    <div class="well col-xs-4">
      <%= form_tag keywords_path, :method => 'get' do %>
        <%= text_field_tag :search_adwords_urls, params[:search_adwords_urls] %>
        <%= submit_tag "Search Adwords URLs" %>
      <% end %>
    </div>

    <div class="well col-xs-4">
      <%= form_tag keywords_path, :method => 'get' do %>
        <%= text_field_tag :search_url, params[:search_url] %>
        <%= submit_tag "Search ALL URLs" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class ='table table-striped table-bordered table-responsive'>
        <legend>Keywords Report</legend>
        <div class="row">
          <div class="col-xs-4">
            <h4>Results: <strong><%=@count%></strong></h4>
          </div>
          <div class="col-xs-4">
            <h4><strong><%= link_to("Download Keywords Report (PDF)", keywords_path(format: "pdf")) %></strong></h4>
          </div>
        </div>
        
        <thead>
          <tr>
            <th>Keyword</th>
            <th>AdWords at Top Position</th>
            <th>AdWords at Bottom Position</th>
            <th>Total Adwords</th>
            <th>Total Non-AdWords</th>
            <th>Total Links</th>
            <th>Total Search Results</th>
            <th>Top AdWords URLs</th>
            <th>Bottom AdWords URLs</th>
            <th>Non-AdWords URLs</th>
            <th>HTML</th>
          </tr>
        </thead>
        <tbody>
          <% @keywords.each do |keyword| %>
          <tr>
            <td><%= keyword.keyword %></td>
            <td><%= keyword.ads_top_num %></td>
            <td><%= keyword.ads_bottom_num %></td>
            <td><%= keyword.ads_total_num %></td>
            <td><%= keyword.non_ads_num %></td>
            <td><%= keyword.total_links_num %></td>
            <td><%= keyword.total_search_results_num %></td>
            <td class="green-url">
              <% keyword.ads_top_urls.each do |url|%>
                <li><%= auto_link(url) %></li>
              <%end%>
            </td>
            <td class="green-url">
              <% keyword.ads_bottom_urls.each do |url|%>
                <li><%= auto_link(url) %></li>
              <%end%>
            </td>
            <td>
              <% keyword.non_ads_urls.each do |url|%>
                <li><%= auto_link(url) %></li>
              <%end%>
            </td>
            <td><%= link_to("View HTML", keyword_path(keyword)) %></td>
          </tr>
          <%end%>
        </tbody>
      <%= will_paginate @keywords %>
      </table>
    </div>
  </div>  
</div>

app/views/keywords/show.html.erb
<div class="container-html">
	<div class="row well">
		<div class="col-md-1">
			<h4>Keyword: </h4>
		</div>
		<div class="col-md-2">
			<h4><%=@keyword.keyword%></h4>
		</div>

		<div class="col-md-2">
			<h4>Total Ads: </h4>
		</div>
		<div class="col-md-2">
			<h4><%=@keyword.ads_total_num%></h4>
		</div>
		
		<div class="col-md-3">
			<h4><%=@keyword.total_search_results_num%></h4>
		</div>
	</div>

	<div class="row row-html">
		<div class="col-md-12">
				<%=@keyword.html.to_s.html_safe%>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><%= link_to "About", '#'%></li>
			<li><%= link_to "Contact", "#" %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to('Google Scraper', root_path, id: "logo") %>
		<nav>
		<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
	            Logged in as <strong><%= current_user.email %></strong>
	            <%= link_to 'Edit profile', edit_user_registration_path %> |
	            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          	<% else %>
	            <%= link_to "Sign up", new_user_registration_path %> |
	            <%= link_to "Login", new_user_session_path %>
          	<% end %>
		</ul>
		</nav>
	</div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleScraping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% if current_user %>
	<div class="row">
		<div class="col-md-12">
	      <h1>
	      <%= link_to 'Scrape Now', keywords_path %>
	    	</h1>
	    </div>
	</div>
<% else %>
	<div class="center jumbotron">
		<h1>Welcome to Google Scrapper!</h1>
		<h2>Scrape google search results and return useful informations</h2>
		<li>Import CSV file contains words you want to scrape</li>
		<li>Browse scrapped results i.e. how many adwords in the page, where it's position, URLs of these ads, URLs of non-ads and more</li>
		<br />
		<%= link_to("Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary") %>
	</div>
<% end %>